"""Aggionata matching_status come integer

Revision ID: 14241b391d8b
Revises: 3c06d9aeb250
Create Date: 2025-11-13 17:53:53.424391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14241b391d8b'
down_revision = '3c06d9aeb250'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('matching_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('matching_status',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
