"""Rimozione tabella match

Revision ID: 1799679fd6ea
Revises: da1755bbb898
Create Date: 2025-11-12 17:09:50.586706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1799679fd6ea'
down_revision = 'da1755bbb898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('mentor_id', sa.INTEGER(), nullable=False),
    sa.Column('mentee_id', sa.INTEGER(), nullable=False),
    sa.Column('match_date', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mentor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
