"""Aggionata tabella user

Revision ID: 3c06d9aeb250
Revises: a410345c77b7
Create Date: 2025-11-12 18:02:34.798689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c06d9aeb250'
down_revision = 'a410345c77b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('mentor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mentee_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('mentee_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('mentor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
