"""Migrazione iniziale, creazione tabelle

Revision ID: ebd081a7add1
Revises: 
Create Date: 2025-11-05 16:57:22.979906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebd081a7add1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('surname', sa.String(length=150), nullable=True),
    sa.Column('university', sa.String(length=150), nullable=True),
    sa.Column('current_status', sa.String(length=150), nullable=True),
    sa.Column('field_of_study', sa.String(length=150), nullable=True),
    sa.Column('participation_role', sa.String(length=150), nullable=True),
    sa.Column('time_commitment', sa.String(length=150), nullable=True),
    sa.Column('communication', sa.String(length=150), nullable=True),
    sa.Column('improve_communication', sa.String(length=150), nullable=True),
    sa.Column('help_writing_paper', sa.String(length=150), nullable=True),
    sa.Column('maximize_conference_experience', sa.String(length=150), nullable=True),
    sa.Column('help_choice_time_abroad', sa.String(length=150), nullable=True),
    sa.Column('phd_work_balance', sa.String(length=150), nullable=True),
    sa.Column('phd_family_balance', sa.String(length=150), nullable=True),
    sa.Column('improve_soft_skills', sa.String(length=150), nullable=True),
    sa.Column('help_academic_career', sa.String(length=150), nullable=True),
    sa.Column('help_industrial_career', sa.String(length=150), nullable=True),
    sa.Column('talk_mental_wellbeing', sa.String(length=150), nullable=True),
    sa.Column('discovery', sa.String(length=150), nullable=True),
    sa.Column('advice', sa.String(length=150), nullable=True),
    sa.Column('promotion_help', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
